channels:
- currentCSV: redhat-marketplace-operator.v0.1.2
  name: beta
- currentCSV: redhat-marketplace-operator.v0.1.4
  name: stable
defaultChannel: stable
packageName: redhat-marketplace-operator
