# permissions for end users to view certissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certissuer-viewer-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - certissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - certissuers/status
  verbs:
  - get
