apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "openshift-redhat-marketplace" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          # Replace this with the built image name
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/auth-service-account
              name: token-vol
              readOnly: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - redhat-marketplace-operator
          env:
            - name: OPERATOR_NAME
              value: {{ .Values.name }}
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_REPORTER
              value: {{ .Values.reporterImage }}
            - name: RELATED_IMAGE_METRIC_STATE
              value: {{ .Values.metricStateImage }}
            - name: RELATED_IMAGE_AUTHCHECK
              value: {{ .Values.authCheckImage }}
            {{- if .Values.env -}}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
      volumes:
        - name: token-vol
          projected:
            sources:
              - serviceAccountToken:
                  audience: rhm-prometheus-meterbase.openshift-redhat-marketplace.svc
                  expirationSeconds: 3600
                  path: token