---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: remoteresources.deploy.razee.io
spec:
  group: deploy.razee.io
  names:
    kind: RemoteResource
    listKind: RemoteResourceList
    plural: remoteresources
    singular: remoteresource
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: RemoteResource is the Schema for the remoteresources API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RemoteResourceSpec defines the desired state of RemoteResource
            properties:
              auth:
                properties:
                  hmac:
                    properties:
                      accessKeyId:
                        type: string
                      accessKeyIdRef:
                        description: AccesKeyIDRef holds reference information to
                          an AccessKeyID stored in a secret on your cluster
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                      secretAccessKey:
                        type: string
                      secretAccessKeyRef:
                        description: SecretAccessKeyRef holds reference information
                          to an SecretAccessKey stored in a secret on your cluster
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                    type: object
                  iam:
                    properties:
                      apiKey:
                        type: string
                      apiKeyRef:
                        description: APIKeyRef holds the location of the api key used
                          to authenticate to a cloud object storage instance
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                      grantType:
                        type: string
                      url:
                        type: string
                    type: object
                type: object
              backendService:
                enum:
                - generic
                - s3
                - git
                type: string
              clusterAuth:
                properties:
                  impersonateUser:
                    type: string
                type: object
              requests:
                items:
                  description: Request holds requests that populate the Requests array
                  properties:
                    message:
                      description: Message of the request
                      type: string
                    optional:
                      description: Optional if downloading or applying a child resource
                        fails, RemoteResource will stop execution and report error
                        to .status. You can allow execution to continue by marking
                        a reference as optional.
                      type: boolean
                    options:
                      description: Options is the configurable options for the request
                      properties:
                        headers:
                          additionalProperties:
                            additionalProperties:
                              type: string
                            description: Header allows you to provide additional information
                              with your reques
                            type: object
                          description: Headers of the request
                          type: object
                        uri:
                          description: URI of the request
                          type: string
                        url:
                          description: URL of the request
                          type: string
                      type: object
                    statusCode:
                      description: Status of the request
                      type: integer
                  type: object
                type: array
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: RemoteResourceS3Status defines the observed state of RemoteResourceS3
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
