---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresources3deployment-binding
subjects:
- kind: ServiceAccount
  name: remoteresources3deployment
  namespace: system
roleRef:
  kind: ClusterRole
  name: remoteresources3deployment
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-binding
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: system
roleRef:
  kind: ClusterRole
  name: prometheus-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-binding
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: system
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-keeper-binding
subjects:
- kind: ServiceAccount
  name: watch-keeper
  namespace: system
roleRef:
  kind: ClusterRole
  name: watch-keeper
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresources3deployment-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: remoteresources3deployment
  namespace: system
roleRef:
  kind: Role
  name: remoteresources3deployment
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: system
roleRef:
  kind: Role
  name: prometheus-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: system
roleRef:
  kind: Role
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
roleRef:
  kind: Role
  name: reporter
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mteric-state-mdef-editor-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: metric-state
  namespace: system
roleRef:
  kind: ClusterRole
  name: meterdefinition-editor-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-state-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: metric-state
  namespace: system
roleRef:
  kind: ClusterRole
  name: metric-state
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-state-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: metric-state
  namespace: system
roleRef:
  kind: Role
  name: metric-state
  apiGroup: rbac.authorization.k8s.io
