# Adds namespace to all resources.
namespace: redhat-marketplace
# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

resources:
  - ../default
  - ../scorecard
  - bases/redhat-marketplace-operator.clusterserviceversion.yaml
