apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  # Add fields here
  rhmCustomerID: example-userid
  clusterUUID: max-rhm-operator-test-9
  deploySecretName: rhm-operator-secret