apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meterdefinitions.marketplace.redhat.com
spec:
  group: marketplace.redhat.com
  names:
    kind: MeterDefinition
    listKind: MeterDefinitionList
    plural: meterdefinitions
    singular: meterdefinition
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MeterDefinition defines the meter workloads used to enable pay
        for use billing.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeterDefinitionSpec defines the desired metering spec
          properties:
            installedBy:
              description: InstalledBy is a reference to the CSV that install the
                meter definition. This is used to determine an operator group.
              properties:
                groupVersionKind:
                  description: GroupVersionKind of the resource
                  properties:
                    apiVersion:
                      description: APIVersion of the CRD
                      type: string
                    kind:
                      description: Kind of the CRD
                      type: string
                  required:
                  - apiVersion
                  - kind
                  type: object
                name:
                  description: Name of the resource Required
                  type: string
                namespace:
                  description: Namespace of the resource Required
                  type: string
                uid:
                  description: Namespace of the resource
                  type: string
              required:
              - name
              - namespace
              type: object
            meterGroup:
              description: Group defines the operator group of the meter
              type: string
            meterKind:
              description: Kind defines the primary CRD kind of the meter
              type: string
            meterVersion:
              description: Version defines the primary CRD version of the meter. This
                field is no longer used.
              type: string
            podMeterLabels:
              description: PodMeterLabels name of the prometheus metrics you want
                to track. User workloads instead.
              items:
                type: string
              type: array
            serviceMeterLabels:
              description: ServiceMeterLabels name of the meterics you want to track.
                Use workloads instead.
              items:
                type: string
              type: array
            workloadVertexLabelSelectors:
              description: VertexFilters are used when Namespace is selected. Can
                be omitted if you select OperatorGroup
              properties:
                matchExpressions:
                  description: matchExpressions is a list of label selector requirements.
                    The requirements are ANDed.
                  items:
                    description: A label selector requirement is a selector that contains
                      values, a key, and an operator that relates the key and values.
                    properties:
                      key:
                        description: key is the label key that the selector applies
                          to.
                        type: string
                      operator:
                        description: operator represents a key's relationship to a
                          set of values. Valid operators are In, NotIn, Exists and
                          DoesNotExist.
                        type: string
                      values:
                        description: values is an array of string values. If the operator
                          is In or NotIn, the values array must be non-empty. If the
                          operator is Exists or DoesNotExist, the values array must
                          be empty. This array is replaced during a strategic merge
                          patch.
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - operator
                    type: object
                  type: array
                matchLabels:
                  additionalProperties:
                    type: string
                  description: matchLabels is a map of {key,value} pairs. A single
                    {key,value} in the matchLabels map is equivalent to an element
                    of matchExpressions, whose key field is "key", the operator is
                    "In", and the values array contains only "value". The requirements
                    are ANDed.
                  type: object
              type: object
            workloadVertexType:
              description: WorkloadVertexType is the top most object of a workload.
                It allows you to identify the upper bounds of your workloads.
              enum:
              - Namespace
              - OperatorGroup
              type: string
            workloads:
              description: Workloads identify the workloads to meter.
              items:
                description: Workload helps identify what to target for metering.
                properties:
                  annotationSelector:
                    description: AnnotationSelector are used to filter to the correct
                      workload.
                    properties:
                      matchExpressions:
                        description: matchExpressions is a list of label selector
                          requirements. The requirements are ANDed.
                        items:
                          description: A label selector requirement is a selector
                            that contains values, a key, and an operator that relates
                            the key and values.
                          properties:
                            key:
                              description: key is the label key that the selector
                                applies to.
                              type: string
                            operator:
                              description: operator represents a key's relationship
                                to a set of values. Valid operators are In, NotIn,
                                Exists and DoesNotExist.
                              type: string
                            values:
                              description: values is an array of string values. If
                                the operator is In or NotIn, the values array must
                                be non-empty. If the operator is Exists or DoesNotExist,
                                the values array must be empty. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: matchLabels is a map of {key,value} pairs. A
                          single {key,value} in the matchLabels map is equivalent
                          to an element of matchExpressions, whose key field is "key",
                          the operator is "In", and the values array contains only
                          "value". The requirements are ANDed.
                        type: object
                    type: object
                  labelSelector:
                    description: LabelSelector are used to filter to the correct workload.
                    properties:
                      matchExpressions:
                        description: matchExpressions is a list of label selector
                          requirements. The requirements are ANDed.
                        items:
                          description: A label selector requirement is a selector
                            that contains values, a key, and an operator that relates
                            the key and values.
                          properties:
                            key:
                              description: key is the label key that the selector
                                applies to.
                              type: string
                            operator:
                              description: operator represents a key's relationship
                                to a set of values. Valid operators are In, NotIn,
                                Exists and DoesNotExist.
                              type: string
                            values:
                              description: values is an array of string values. If
                                the operator is In or NotIn, the values array must
                                be non-empty. If the operator is Exists or DoesNotExist,
                                the values array must be empty. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: matchLabels is a map of {key,value} pairs. A
                          single {key,value} in the matchLabels map is equivalent
                          to an element of matchExpressions, whose key field is "key",
                          the operator is "In", and the values array contains only
                          "value". The requirements are ANDed.
                        type: object
                    type: object
                  metricLabels:
                    description: MetricLabels are the labels to collect
                    items:
                      description: MeterLabelQuery helps define a meter label to build
                        and search for
                      properties:
                        aggregation:
                          description: Aggregation to use with the query
                          enum:
                          - sum
                          - min
                          - max
                          - avg
                          type: string
                        label:
                          description: Label is the name of the meter
                          type: string
                        query:
                          description: Query to use for the label
                          type: string
                      required:
                      - label
                      type: object
                    minItems: 1
                    type: array
                  name:
                    description: Name of the workload, must be unique in a meter definition.
                    type: string
                  ownerCRD:
                    description: OwnerCRD is the name of the GVK to look for as the
                      owner of all the meterable assets. If omitted, the labels and
                      annotations are used instead.
                    properties:
                      apiVersion:
                        description: APIVersion of the CRD
                        type: string
                      kind:
                        description: Kind of the CRD
                        type: string
                    required:
                    - apiVersion
                    - kind
                    type: object
                  type:
                    description: WorkloadType identifies the type of workload to look
                      for. This can be pod or service right now.
                    enum:
                    - Pod
                    - Service
                    - PersistentVolumeClaim
                    type: string
                required:
                - name
                - type
                type: object
              minItems: 1
              type: array
          required:
          - meterGroup
          - meterKind
          type: object
        status:
          description: MeterDefinitionStatus defines the observed state of MeterDefinition
          properties:
            conditions:
              description: Conditions represent the latest available observations
                of an object's state
              items:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            results:
              description: Results is the result of the queries defined on the meterdefinition.
                This will generate data for the previous 3 hours on whichever workload
                you specify This is intended to be a preview to check whether a query
                is working as intended.
              items:
                description: Result
                properties:
                  MetricData:
                    format: int32
                    type: integer
                  endTime:
                    type: string
                  queryName:
                    type: string
                  startTime:
                    type: string
                  workloadName:
                    type: string
                type: object
              type: array
            workloadResource:
              description: WorkloadResources is the list of resoruces discovered by
                this meter definition
              items:
                properties:
                  groupVersionKind:
                    description: GroupVersionKind of the resource
                    properties:
                      apiVersion:
                        description: APIVersion of the CRD
                        type: string
                      kind:
                        description: Kind of the CRD
                        type: string
                    required:
                    - apiVersion
                    - kind
                    type: object
                  name:
                    description: Name of the resource Required
                    type: string
                  namespace:
                    description: Namespace of the resource Required
                    type: string
                  referencedWorkloadName:
                    type: string
                  uid:
                    description: Namespace of the resource
                    type: string
                required:
                - name
                - namespace
                - referencedWorkloadName
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
