apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  # Add fields here 
  rhmAccountID: example-userid
  clusterUUID: example-clusterUUID
  deploySecretName: example-deploySecretName
