apiVersion: marketplace.redhat.com/v1alpha1
kind: MeterBase
metadata:
  name: example-meterbase
spec:
  enabled: true
  prometheus:
    # Resource limits for the prometheus instance. Recommended:
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1G
    # Storage used for PVC, recommended default is 20Gi
    storage:
      enabled: true
      # class defaults to null, which means using the default storage
      # class.
      # If you have a storageClass which provides SSDs, uncomment and
      # specify it here:
      # class: "fast-ssd"
      # The default size of 5Gi is fairly small. With 1000 namespaces and
      # at least 5 pods per namespace you could expect a few hundred Mb of
      # storage per week.
      # With multiple replicas, storage capacity is also increased.
      # Additionally, on many clouds, IOPS are provisioned based on disk
      # size, meaning a larger PVC can be faster.
      size: '20Gi'
    # uncomment if you want to limit the nodes it will be running on
    # nodeSelector:
    #   "node-role.kubernetes.io/infra": "true"
