apiVersion: marketplace.redhat.com/v1alpha1
kind: RazeeDeployment
metadata:
  name: rhm-marketplaceconfig-razeedeployment
spec:
  # Add fields here
  enabled: true
  clusterUUID:  max-rhm-operator-test-9
  deploySecretName: rhm-operator-secret
