---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redhat-marketplace-operator
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
roleRef:
  kind: ClusterRole
  name: redhat-marketplace-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redhat-marketplace-remoteresources3deployment
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-remoteresources3deployment
  namespace: openshift-redhat-marketplace
roleRef:
  kind: ClusterRole
  name: redhat-marketplace-remoteresources3deployment
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redhat-marketplace-watch-keeper
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-watch-keeper
  namespace: openshift-redhat-marketplace
roleRef:
  kind: ClusterRole
  name: redhat-marketplace-watch-keeper
  apiGroup: rbac.authorization.k8s.io
---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
roleRef:
  kind: Role
  name: redhat-marketplace-operator
  apiGroup: rbac.authorization.k8s.io
