---
# Source: redhat-marketplace-operator-template-chart/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redhat-marketplace-operator
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
    redhat.marketplace.com/version: 0.0.2
---
# Source: redhat-marketplace-operator-template-chart/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redhat-marketplace-razeedeploy
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
    redhat.marketplace.com/version: 0.0.2
---
# Source: redhat-marketplace-operator-template-chart/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redhat-marketplace-operator
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
    redhat.marketplace.com/version: 0.0.2
